import { Template, TemplateField } from './database';

// Predefined system templates for common health surveys
export const SYSTEM_TEMPLATES: Omit<Template, 'synced'>[] = [
  {
    id: 'template_general_health',
    name: 'General Health Assessment',
    description: 'Basic health assessment for general checkups',
    is_system: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    fields: [
      {
        id: 'field_blood_pressure',
        type: 'text',
        label: 'Blood Pressure',
        placeholder: 'e.g., 120/80',
        validation: { required: true },
        order: 1,
      },
      {
        id: 'field_heart_rate',
        type: 'number',
        label: 'Heart Rate (bpm)',
        placeholder: 'e.g., 72',
        validation: { required: true, minValue: 30, maxValue: 200 },
        order: 2,
      },
      {
        id: 'field_temperature',
        type: 'number',
        label: 'Temperature (°C)',
        placeholder: 'e.g., 98.6',
        validation: { required: true, minValue: 35, maxValue: 42 },
        order: 3,
      },
      {
        id: 'field_weight',
        type: 'number',
        label: 'Weight (kg)',
        placeholder: 'e.g., 65',
        validation: { required: false, minValue: 1, maxValue: 300 },
        order: 4,
      },
      {
        id: 'field_height',
        type: 'number',
        label: 'Height (cm)',
        placeholder: 'e.g., 170',
        validation: { required: false, minValue: 50, maxValue: 250 },
        order: 5,
      },
      {
        id: 'field_symptoms',
        type: 'text',
        label: 'Current Symptoms',
        placeholder: 'Describe any symptoms',
        validation: { required: false, maxLength: 500 },
        order: 6,
      },
      {
        id: 'field_notes',
        type: 'text',
        label: 'Additional Notes',
        placeholder: 'Any other observations',
        validation: { required: false, maxLength: 1000 },
        order: 7,
      },
    ],
  },
  {
    id: 'template_maternal_health',
    name: 'Maternal Health Survey',
    description: 'Health assessment for pregnant women and mothers',
    is_system: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    fields: [
      {
        id: 'field_pregnancy_week',
        type: 'number',
        label: 'Pregnancy Week',
        placeholder: 'e.g., 20',
        validation: { required: true, minValue: 1, maxValue: 42 },
        order: 1,
      },
      {
        id: 'field_last_menstrual',
        type: 'date',
        label: 'Last Menstrual Period',
        validation: { required: true },
        order: 2,
      },
      {
        id: 'field_blood_pressure',
        type: 'text',
        label: 'Blood Pressure',
        placeholder: 'e.g., 120/80',
        validation: { required: true },
        order: 3,
      },
      {
        id: 'field_hemoglobin',
        type: 'number',
        label: 'Hemoglobin Level (g/dL)',
        placeholder: 'e.g., 12.5',
        validation: { required: false, minValue: 5, maxValue: 20 },
        order: 4,
      },
      {
        id: 'field_weight',
        type: 'number',
        label: 'Current Weight (kg)',
        placeholder: 'e.g., 60',
        validation: { required: true, minValue: 30, maxValue: 200 },
        order: 5,
      },
      {
        id: 'field_complications',
        type: 'dropdown',
        label: 'Any Complications',
        validation: {
          required: false,
          options: ['None', 'Gestational Diabetes', 'Preeclampsia', 'Anemia', 'Other'],
        },
        order: 6,
      },
      {
        id: 'field_antenatal_visits',
        type: 'number',
        label: 'Number of Antenatal Visits',
        placeholder: 'e.g., 4',
        validation: { required: true, minValue: 0, maxValue: 20 },
        order: 7,
      },
      {
        id: 'field_notes',
        type: 'text',
        label: 'Additional Notes',
        placeholder: 'Any other observations',
        validation: { required: false, maxLength: 1000 },
        order: 8,
      },
    ],
  },
  {
    id: 'template_child_health',
    name: 'Child Health Survey',
    description: 'Health assessment for children under 5 years',
    is_system: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    fields: [
      {
        id: 'field_child_age_months',
        type: 'number',
        label: 'Child Age (months)',
        placeholder: 'e.g., 24',
        validation: { required: true, minValue: 0, maxValue: 60 },
        order: 1,
      },
      {
        id: 'field_weight',
        type: 'number',
        label: 'Weight (kg)',
        placeholder: 'e.g., 12',
        validation: { required: true, minValue: 1, maxValue: 30 },
        order: 2,
      },
      {
        id: 'field_height',
        type: 'number',
        label: 'Height/Length (cm)',
        placeholder: 'e.g., 85',
        validation: { required: true, minValue: 30, maxValue: 120 },
        order: 3,
      },
      {
        id: 'field_muac',
        type: 'number',
        label: 'MUAC (cm)',
        placeholder: 'Mid-Upper Arm Circumference',
        validation: { required: false, minValue: 5, maxValue: 25 },
        order: 4,
      },
      {
        id: 'field_vaccination_status',
        type: 'dropdown',
        label: 'Vaccination Status',
        validation: {
          required: true,
          options: ['Up to date', 'Partially vaccinated', 'Not vaccinated', 'Unknown'],
        },
        order: 5,
      },
      {
        id: 'field_breastfeeding',
        type: 'dropdown',
        label: 'Breastfeeding Status',
        validation: {
          required: false,
          options: ['Exclusive breastfeeding', 'Partial breastfeeding', 'Not breastfeeding'],
        },
        order: 6,
      },
      {
        id: 'field_illness',
        type: 'dropdown',
        label: 'Recent Illness',
        validation: {
          required: false,
          options: ['None', 'Fever', 'Diarrhea', 'Respiratory infection', 'Malaria', 'Other'],
        },
        order: 7,
      },
      {
        id: 'field_notes',
        type: 'text',
        label: 'Additional Notes',
        placeholder: 'Any other observations',
        validation: { required: false, maxLength: 1000 },
        order: 8,
      },
    ],
  },
  {
    id: 'template_chronic_disease',
    name: 'Chronic Disease Management',
    description: 'Assessment for patients with chronic conditions',
    is_system: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    fields: [
      {
        id: 'field_condition',
        type: 'dropdown',
        label: 'Chronic Condition',
        validation: {
          required: true,
          options: ['Diabetes', 'Hypertension', 'Heart Disease', 'Asthma', 'COPD', 'TB', 'Other'],
        },
        order: 1,
      },
      {
        id: 'field_diagnosis_date',
        type: 'date',
        label: 'Date of Diagnosis',
        validation: { required: true },
        order: 2,
      },
      {
        id: 'field_blood_pressure',
        type: 'text',
        label: 'Blood Pressure',
        placeholder: 'e.g., 120/80',
        validation: { required: false },
        order: 3,
      },
      {
        id: 'field_blood_sugar',
        type: 'number',
        label: 'Blood Sugar (mg/dL)',
        placeholder: 'Fasting or random',
        validation: { required: false, minValue: 40, maxValue: 600 },
        order: 4,
      },
      {
        id: 'field_medication_adherence',
        type: 'dropdown',
        label: 'Medication Adherence',
        validation: {
          required: true,
          options: ['Regular', 'Irregular', 'Not taking medication', 'No medication prescribed'],
        },
        order: 5,
      },
      {
        id: 'field_symptoms',
        type: 'text',
        label: 'Current Symptoms',
        placeholder: 'Describe any symptoms',
        validation: { required: false, maxLength: 500 },
        order: 6,
      },
      {
        id: 'field_last_visit',
        type: 'date',
        label: 'Last Hospital Visit',
        validation: { required: false },
        order: 7,
      },
      {
        id: 'field_notes',
        type: 'text',
        label: 'Additional Notes',
        placeholder: 'Any other observations',
        validation: { required: false, maxLength: 1000 },
        order: 8,
      },
    ],
  },
  {
    id: 'template_disease_surveillance',
    name: 'Disease Surveillance',
    description: 'For tracking infectious diseases and outbreaks',
    is_system: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    fields: [
      {
        id: 'field_disease_type',
        type: 'dropdown',
        label: 'Suspected Disease',
        validation: {
          required: true,
          options: ['Malaria', 'Dengue', 'Chikungunya', 'Typhoid', 'Cholera', 'COVID-19', 'Other'],
        },
        order: 1,
      },
      {
        id: 'field_symptom_onset',
        type: 'date',
        label: 'Symptom Onset Date',
        validation: { required: true },
        order: 2,
      },
      {
        id: 'field_fever',
        type: 'dropdown',
        label: 'Fever Present',
        validation: {
          required: true,
          options: ['Yes', 'No'],
        },
        order: 3,
      },
      {
        id: 'field_temperature',
        type: 'number',
        label: 'Temperature (°C)',
        placeholder: 'e.g., 38.5',
        validation: { required: false, minValue: 35, maxValue: 42 },
        order: 4,
      },
      {
        id: 'field_other_symptoms',
        type: 'text',
        label: 'Other Symptoms',
        placeholder: 'List all symptoms',
        validation: { required: false, maxLength: 500 },
        order: 5,
      },
      {
        id: 'field_travel_history',
        type: 'text',
        label: 'Travel History (last 14 days)',
        placeholder: 'Places visited',
        validation: { required: false, maxLength: 300 },
        order: 6,
      },
      {
        id: 'field_contact_history',
        type: 'text',
        label: 'Contact with Similar Cases',
        placeholder: 'Known contacts',
        validation: { required: false, maxLength: 300 },
        order: 7,
      },
      {
        id: 'field_sample_collected',
        type: 'dropdown',
        label: 'Sample Collected',
        validation: {
          required: false,
          options: ['Yes', 'No', 'Pending'],
        },
        order: 8,
      },
      {
        id: 'field_notes',
        type: 'text',
        label: 'Additional Notes',
        placeholder: 'Any other observations',
        validation: { required: false, maxLength: 1000 },
        order: 9,
      },
    ],
  },
  {
    id: 'template_wound_care',
    name: 'Wound Care Assessment',
    description: 'For documenting and tracking wound healing',
    is_system: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    fields: [
      {
        id: 'field_wound_type',
        type: 'dropdown',
        label: 'Wound Type',
        validation: {
          required: true,
          options: ['Surgical', 'Traumatic', 'Pressure Ulcer', 'Diabetic Ulcer', 'Burn', 'Other'],
        },
        order: 1,
      },
      {
        id: 'field_wound_location',
        type: 'text',
        label: 'Wound Location',
        placeholder: 'e.g., Left leg, lower',
        validation: { required: true, maxLength: 100 },
        order: 2,
      },
      {
        id: 'field_wound_size',
        type: 'text',
        label: 'Wound Size (L x W cm)',
        placeholder: 'e.g., 5 x 3',
        validation: { required: true },
        order: 3,
      },
      {
        id: 'field_wound_depth',
        type: 'dropdown',
        label: 'Wound Depth',
        validation: {
          required: true,
          options: ['Superficial', 'Partial thickness', 'Full thickness', 'Deep'],
        },
        order: 4,
      },
      {
        id: 'field_exudate',
        type: 'dropdown',
        label: 'Exudate Amount',
        validation: {
          required: true,
          options: ['None', 'Minimal', 'Moderate', 'Heavy'],
        },
        order: 5,
      },
      {
        id: 'field_infection_signs',
        type: 'dropdown',
        label: 'Signs of Infection',
        validation: {
          required: true,
          options: ['None', 'Redness', 'Swelling', 'Pus', 'Foul odor', 'Multiple signs'],
        },
        order: 6,
      },
      {
        id: 'field_wound_photo',
        type: 'image',
        label: 'Wound Photo',
        validation: { required: true },
        order: 7,
      },
      {
        id: 'field_treatment',
        type: 'text',
        label: 'Treatment Given',
        placeholder: 'Describe treatment',
        validation: { required: false, maxLength: 500 },
        order: 8,
      },
      {
        id: 'field_notes',
        type: 'text',
        label: 'Additional Notes',
        placeholder: 'Any other observations',
        validation: { required: false, maxLength: 1000 },
        order: 9,
      },
    ],
  },
];

// Function to seed system templates into database
export const seedSystemTemplates = async (insertTemplate: (template: Omit<Template, 'synced'>) => Promise<void>) => {
  for (const template of SYSTEM_TEMPLATES) {
    try {
      await insertTemplate(template);
      console.log(`✅ Seeded template: ${template.name}`);
    } catch (error) {
      console.log(`⚠️ Template ${template.name} may already exist, skipping...`);
    }
  }
};
